version: 0.2

phases:
  install:
    commands:
      - yum install -y jq
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/l7l3w4g3
      - REPOSITORY_URI=public.ecr.aws/l7l3w4g3/mypublicrepo
                       
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      #- docker build -t 596343352176.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$Repository_Name-$Branch_Name:$CODEBUILD_BUILD_NUMBER .
      - docker build -t mypublicrepo .
      - docker tag mypublicrepo:latest public.ecr.aws/l7l3w4g3/mypublicrepo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      #- docker push 596343352176.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$Repository_Name-$Branch_Name:$CODEBUILD_BUILD_NUMBER
      - docker push public.ecr.aws/l7l3w4g3/mypublicrepo:latest
      - echo Writing image definitions file...
      #- echo "$Repository_Name-$Branch_Name"
      - printf '[{"name":"%s","imageUri":"%s"}]' $Repository_Name-$Branch_Name-container $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER > imagedefinitions.json
      
artifacts:
  files: 
    # - 'imageDetail.json'
    - 'imagedefinitions.json'
