version: 0.2

phases:
  install:
    commands:
      - yum install -y jq
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 240077723373.dkr.ecr.us-west-1.amazonaws.com
      - REPOSITORY_URI=240077723373.dkr.ecr.us-west-1.amazonaws.com/sample-repo-master
                       
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      #- docker build -t 596343352176.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$Repository_Name-$Branch_Name:$CODEBUILD_BUILD_NUMBER .
      - docker build -t sample-image:$CODEBUILD_BUILD_NUMBER .
      - docker tag sample-image:$CODEBUILD_BUILD_NUMBER 240077723373.dkr.ecr.us-west-1.amazonaws.com/sample-repo-master:$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      #- docker push 596343352176.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$Repository_Name-$Branch_Name:$CODEBUILD_BUILD_NUMBER
      - docker push 240077723373.dkr.ecr.us-west-1.amazonaws.com/sample-repo-master:$CODEBUILD_BUILD_NUMBER
      - echo Writing image definitions file...
      - echo "$Repository_Name-$Branch_Name"
      - printf '[{"name":"%s","imageUri":"%s"}]' $Repository_Name-$Branch_Name-container $REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER > imagedefinitions.json
      
artifacts:
  files: 
    # - 'imageDetail.json'
    - 'imagedefinitions.json'
